### ISSUE TITLE
Every step followed, still getting errors

### ISSUE THREAD

**Issue by ParthSalat47** [alejandro-du/covid-dashboard#18]
## Before installing nodejs and npm, the error was as follows:
![image](https://user-images.githubusercontent.com/62230055/125418784-e737071d-5476-441d-ad18-db59aaca946d.png)

## After installing nodejs and npm, the error was as follows: 
![image](https://user-images.githubusercontent.com/62230055/125418893-6694584d-779d-4030-85be-fb9905f91475.png)

I've followed every required step, still facing this issue. Any changes I need to make, for this to work?

Thanks.

**Comment by viren-sureja** [comment]
I followed the same step still getting error

**Comment by alejandro-du** [comment]
Di you download your own copy of the GeoLite2 Cities database?

**Comment by ParthSalat47** [comment]
Yes downloaded my own copy and placed it at the correct place

**Comment by alejandro-du** [comment]
Please compile with JDK 15 or later and share here what was `null`.
