### ISSUE TITLE
[Question] Data storage

### ISSUE THREAD

**Issue by nivramam** [alejandro-du/covid-dashboard#21]
Hi, I am Niveydhithaa, a CS college student. I just came across your dashboard while browsing for my course assignment and it seems pretty cool! 

I have a question regarding the data storage. How are you managing to store this COVID cases data? And are you storing country-wise? Thanks a lot in advance, it will help me a lot!

**Comment by alejandro-du** [comment]
Hi, the application doesn't store any data. It consumes a public [web service](https://about-corona.net/documentation). Here's a blog post that explains how to develop the application: https://vaadin.com/blog/building-a-dashboard-for-a-rest-web-service-in-java.

**Comment by nivramam** [comment]
Sure, will take a look into it!!Thanks a lot!
